server:
  port: 8081

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:mysql://localhost:3306/totp_auth
    username: root
    password: Saumieee@18



  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true