server:
  port: 8082

spring:
  application:
    name: auth-service

jwt:
  secret: thisIsMyVerySecretJwtKeyForThisProject
  expiration: 3600000

aes:
  secret-key: 1234567890123456

user-service:
  base-url: http://localhost:8081/users/